server:
  # 服务端口
  port: 8084
  tomcat:
    max-http-post-size: 100MB  #请求参数长度
    max-http-form-post-size: 100MB #form表单长度
  servlet:
    context-path: /hlwfzjz
# 管理端点
management:
  server:
    port: 54305

# Spring 配置相关
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.1.110.96:5432/postgres?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: postgres
    password: Hiko@20201204
  # 文件上传总配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 256MB
  static-dir: /mnt/vos-ev6rjhbg/project/chengyang/hlwfzjz/static
  web:
    resources:
      static-locations:
        - file://${spring.static-dir}
        - classpath:/static/
        - classpath:/public/
        - classpath:/resources/
        - classpath:/META-INF/resources/

#本地+一体机路径
file:
  uploadPath: /mnt/vos-ev6rjhbg/project/chengyang/hlwfzjz/java/filepath/
  uploadMediaPath: /mnt/vos-ev6rjhbg/project/chengyang/hlwfzjz/java/filepath/media/
  taskPath: /mnt/vos-ev6rjhbg/project/chengyang/hlwfzjz/java/filepath/task/
#file:
#  uploadPath: http://10.1.108.219:9004/filePath/
#  uploadMediaPath: http://10.1.108.219:9004/filePath/media/
#  taskPath: http://10.1.108.219:9004/filePath/task/
#font:
#  chinese: C:\Windows\Fonts\