# Spring 配置相关
spring:
  # 数据源配置
  datasource:
    url: jdbc:p6spy:postgresql://192.168.1.203:5432/geovis-fire-product
    username: postgres
    password: postgres
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  # redis配置
  redis:
    host: 192.168.1.203
    password: 123456
# swaager增强功能
knife4j:
  enable: true

